Write-Host ' __  __  _____     _      ______          _____  _   _';
Write-Host '|  \/  |/ ____|   | |    |  ____|   /\   |  __ \| \ | |';
Write-Host '| \  / | (___     | |    | |__     /  \  | |__) |  \| |';
Write-Host '| |\/| |\___ \    | |    |  __|   / /\ \ |  _  /| . ` |';
Write-Host '| |  | |____) |   | |____| |____ / ____ \| | \ \| |\  |';
Write-Host '|_|  |_|_____/____|______|______/_/   _\_\_|_ \_\_| \_|';
Write-Host '';
Write-Host ' _   _______ _____     _______ ____   ____  _';
Write-Host '| | |__   __|_   _|   |__   __/ __ \ / __ \| |';
Write-Host '| |    | |    | |        | | | |  | | |  | | |';
Write-Host '| |    | |    | |        | | | |  | | |  | | |';
Write-Host '| |____| |   _| |_       | | | |__| | |__| | |____';
Write-Host '|______|_|  |_____|      |_|  \____/ \____/|______|';
Write-Host '';
Write-Host '=====================';
Write-Host 'Creating App Registration';
Write-Host '=====================';
Write-Host '';
Write-Host 'Runing Az Cli Commands';
Write-Host '-------------------';

$appinfo=$(az ad app create --display-name MSL-Learn-Lti) | ConvertFrom-Json;
az ad app update --id $appinfo.appId --identifier-uris "api://$($appinfo.appId)";
Write-Host '=========App Registration Info============';
Write-Host '';
Write-Host "Your Client Id --> $($appinfo.appId)";
Write-Host '';
Write-Host "Your Api URI --> $($appinfo.identifierUris)";
Write-Host '';
Write-Host '==========================================';
